import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'
import { Navbar } from '&/components/navbar'
import { Toaster } from '&/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={GeistSans.className}>
        <div className='min-h-screen bg-gray-100 flex flex-col'>
          <Navbar />
          <main className='flex-grow p-6'>{children}</main>
          <Toaster />
        </div>
      </body>
    </html>
  )
}
